# Test env print & function
import environment.alternator_world as ev

a = ev.AlternatorWorld(28, 28, (3, 3))

b, c = a.start()

d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)
d = a.step(2)
d = a.step(1)

m = a.get_seen_mask()

a.dump_seen("/home/sauce/img.png")
